### ISSUE TITLE
Process most likely crashed. Contact support.

### ISSUE THREAD

**Issue by gmrtpfb** [intiface/intiface-desktop#153]
I'm a foreigner, so I'll use a translator.

After installation, I didn't touch the setting and it works well until the server starts, but there is a problem with the device scan.

Turning Bluetooth off on Bluetooth and the device does not cause errors, but then the device is not found.

I watched the video, but I don't know.
[intifacelog.txt](https://github.com/intiface/intiface-desktop/files/7887518/intifacelog.txt)

![image](https://user-images.githubusercontent.com/66209250/149902484-0ecffd2f-c35b-48dd-94b3-3e1be95c63d9.png)

**Comment by qdot** [comment]
You most likely need to update windows. If you run `winver` and check the build version, it needs to be 20H2 or higher. Older builds no longer work.

**Comment by LeGrosFromage** [comment]
I'm having the same issue on a clean build of Fedora 36 (and beta 37) - this is what happens after I scan for devices:

`(node:25049) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined
    at Function.byteLength (buffer.js:728:11)
    at i.string (/home/phil/Downloads/intiface-desktop-27.0.0-linux-x64/resources/app.asar/background.js:2:1258464)
    at Function.e.encode (/home/phil/Downloads/intiface-desktop-27.0.0-linux-x64/resources/app.asar/background.js:2:155530)
    at Function.e.encode (/home/phil/Downloads/intiface-desktop-27.0.0-linux-x64/resources/app.asar/background.js:2:134939)
    at Ot.SendMessage (/home/phil/Downloads/intiface-desktop-27.0.0-linux-x64/resources/app.asar/background.js:2:2273326)
    at /home/phil/Downloads/intiface-desktop-27.0.0-linux-x64/resources/app.asar/background.js:2:2378349
(node:25049) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25049) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/home/phil/.config/IntifaceDesktop/engine/IntifaceCLI
{"logType":"backend","location":"N","message":"Running /home/phil/.config/IntifaceDesktop/engine/IntifaceCLI --servername Intiface Server --deviceconfig /home/phil/.config/IntifaceDesktop/buttplug-device-config.json --frontendpipe --stayopen --wsinsecureport 12345 --log Info --without-hid --without-lovense-dongle-hid --without-lovense-dongle-serial --without-serial","level":"info","timestamp":"2022-10-07T20:52:27.718Z"}
{"logType":"backend","location":"N","message":"Server process exited.","level":"debug","timestamp":"2022-10-07T20:52:27.726Z"}
{"logType":"backend","location":"St","message":"Did not receive process ended message, process most likely crashed.","level":"error","timestamp":"2022-10-07T20:52:27.726Z"}`
