### ISSUE TITLE
Can't connect to Lovense Max 2

### ISSUE THREAD

**Issue by prfeigan** [intiface/intiface-desktop#68]
When scanning for devices Intiface can pair with my Max 2, but never makes it far enough to send a DeviceAdded message.  

I was writing a java.websocket/tyrus client, but most of my tests have used the playground.buttplug.world client.  After starting the server and clicking on CONNECT TO INTIFACE DESKTOP the light on the toy stopped flashing, but the device never appears on the playground device list.  The CONNECT IN BROWSER button has similar behavior (after selecting the device to pair).  

The Lovense Remote app works fine so I don't suspect a problem with the hardware.  

Intiface Desktop Version: 16.0.0
OS: Windows 10
Max 2 purchase date: 7/29/2019

<details><summary>Server Log </summary>
<pre>
2019-08-18T03:23:13.875Z : backend : ServerProcess : Process Log: Got JSON Message: [{"RequestServerInfo":{"Id":1,"ClientName":"Buttplug Playground","MessageVersion":1}}]
2019-08-18T03:23:13.876Z : process : Process : Got JSON Message: [{"RequestServerInfo":{"Id":1,"ClientName":"Buttplug Playground","MessageVersion":1}}]
2019-08-18T03:23:13.923Z : backend : ServerProcess : Process Log: Message successfully parsed as RequestServerInfo type
2019-08-18T03:23:13.924Z : process : Process : Message successfully parsed as RequestServerInfo type
2019-08-18T03:23:13.926Z : backend : ServerProcess : Process Log: Got Message 1 of type RequestServerInfo to send
2019-08-18T03:23:13.927Z : process : Process : Got Message 1 of type RequestServerInfo to send
2019-08-18T03:23:13.926Z : backend : ServerProcess : Process Log: Got RequestServerInfo message.
2019-08-18T03:23:13.927Z : process : Process : Got RequestServerInfo message.
2019-08-18T03:23:13.977Z : backend : ServerProcess : Process Log: Got JSON Message: [{"RequestDeviceList":{"Id":2}}]
2019-08-18T03:23:13.978Z : process : Process : Got JSON Message: [{"RequestDeviceList":{"Id":2}}]
2019-08-18T03:23:13.982Z : backend : ServerProcess : Process Log: Message successfully parsed as RequestDeviceList type
2019-08-18T03:23:13.983Z : process : Process : Message successfully parsed as RequestDeviceList type
2019-08-18T03:23:13.982Z : backend : ServerProcess : Process Log: Got Message 2 of type RequestDeviceList to send
2019-08-18T03:23:13.983Z : process : Process : Got Message 2 of type RequestDeviceList to send
2019-08-18T03:23:13.982Z : backend : ServerProcess : Process Log: Got RequestDeviceList message.
2019-08-18T03:23:13.984Z : process : Process : Got RequestDeviceList message.
2019-08-18T03:23:13.987Z : backend : ServerProcess : Process Log: Got RequestDeviceList Message
2019-08-18T03:23:13.988Z : process : Process : Got RequestDeviceList Message
2019-08-18T03:23:13.997Z : backend : ServerProcess : Process Log: Got JSON Message: [{"StartScanning":{"Id":3}}]
2019-08-18T03:23:13.998Z : process : Process : Got JSON Message: [{"StartScanning":{"Id":3}}]
2019-08-18T03:23:13.998Z : backend : ServerProcess : Process Log: Message successfully parsed as StartScanning type
2019-08-18T03:23:13.999Z : process : Process : Message successfully parsed as StartScanning type
2019-08-18T03:23:13.998Z : backend : ServerProcess : Process Log: Got Message 3 of type StartScanning to send
2019-08-18T03:23:13.999Z : process : Process : Got Message 3 of type StartScanning to send
2019-08-18T03:23:13.998Z : backend : ServerProcess : Process Log: Got StartScanning message.
2019-08-18T03:23:13.999Z : process : Process : Got StartScanning message.
2019-08-18T03:23:13.998Z : backend : ServerProcess : Process Log: Got StartScanning Message
2019-08-18T03:23:14.000Z : process : Process : Got StartScanning Message
2019-08-18T03:23:14.002Z : backend : ServerProcess : Process Log: Searching for Subtype Managers
2019-08-18T03:23:14.003Z : process : Process : Searching for Subtype Managers
2019-08-18T03:23:14.002Z : backend : ServerProcess : Process Log: Searching D:\Documents\SS\IntifaceCLI for Subtype Managers
2019-08-18T03:23:14.004Z : process : Process : Searching D:\Documents\SS\IntifaceCLI for Subtype Managers
2019-08-18T03:23:14.002Z : backend : ServerProcess : Process Log: Loading D:\Documents\SS\IntifaceCLI\Buttplug.Server.Managers.HidSharpManager.dll
2019-08-18T03:23:14.004Z : process : Process : Loading D:\Documents\SS\IntifaceCLI\Buttplug.Server.Managers.HidSharpManager.dll
2019-08-18T03:23:14.006Z : backend : ServerProcess : Process Log: Loading D:\Documents\SS\IntifaceCLI\Buttplug.Server.Managers.UWPBluetoothManager.dll
2019-08-18T03:23:14.006Z : process : Process : Loading D:\Documents\SS\IntifaceCLI\Buttplug.Server.Managers.UWPBluetoothManager.dll
2019-08-18T03:23:14.006Z : backend : ServerProcess : Process Log: Loading D:\Documents\SS\IntifaceCLI\Buttplug.Server.Managers.WinUSBManager.dll
2019-08-18T03:23:14.007Z : process : Process : Loading D:\Documents\SS\IntifaceCLI\Buttplug.Server.Managers.WinUSBManager.dll
2019-08-18T03:23:14.007Z : backend : ServerProcess : Process Log: Loading D:\Documents\SS\IntifaceCLI\Buttplug.Server.Managers.XInputGamepadManager.dll
2019-08-18T03:23:14.007Z : process : Process : Loading D:\Documents\SS\IntifaceCLI\Buttplug.Server.Managers.XInputGamepadManager.dll
2019-08-18T03:23:14.015Z : backend : ServerProcess : Process Log: Adding subtype manager TestDeviceSubtypeManager as part of AddAllSubtypeManagers.
2019-08-18T03:23:14.016Z : process : Process : Adding subtype manager TestDeviceSubtypeManager as part of AddAllSubtypeManagers.
2019-08-18T03:23:14.015Z : backend : ServerProcess : Process Log: Subtype manager TestDeviceSubtypeManager not added, missing appropriate constructor.
2019-08-18T03:23:14.016Z : process : Process : Subtype manager TestDeviceSubtypeManager not added, missing appropriate constructor.
2019-08-18T03:23:14.059Z : backend : ServerProcess : Process Log: Adding subtype manager HidSharpManager as part of AddAllSubtypeManagers.
2019-08-18T03:23:14.060Z : process : Process : Adding subtype manager HidSharpManager as part of AddAllSubtypeManagers.
2019-08-18T03:23:14.060Z : backend : ServerProcess : Process Log: Setting up Device Manager HidSharpManager
2019-08-18T03:23:14.060Z : process : Process : Setting up Device Manager HidSharpManager
2019-08-18T03:23:14.061Z : backend : ServerProcess : Process Log: Adding HidSharpManager subtype manager
2019-08-18T03:23:14.062Z : process : Process : Adding HidSharpManager subtype manager
2019-08-18T03:23:14.070Z : backend : ServerProcess : Process Log: Adding subtype manager UWPBluetoothManager as part of AddAllSubtypeManagers.
2019-08-18T03:23:14.071Z : process : Process : Adding subtype manager UWPBluetoothManager as part of AddAllSubtypeManagers.
2019-08-18T03:23:14.075Z : backend : ServerProcess : Process Log: Setting up Device Manager UWPBluetoothManager
2019-08-18T03:23:14.076Z : process : Process : Setting up Device Manager UWPBluetoothManager
2019-08-18T03:23:14.075Z : backend : ServerProcess : Process Log: Loading UWP Bluetooth Manager
2019-08-18T03:23:14.076Z : process : Process : Loading UWP Bluetooth Manager
2019-08-18T03:23:14.081Z : backend : ServerProcess : Process Log: UWP Manager found working Bluetooth LE Adapter
2019-08-18T03:23:14.087Z : process : Process : UWP Manager found working Bluetooth LE Adapter
2019-08-18T03:23:14.082Z : backend : ServerProcess : Process Log: Adding UWPBluetoothManager subtype manager
2019-08-18T03:23:14.087Z : process : Process : Adding UWPBluetoothManager subtype manager
2019-08-18T03:23:14.082Z : backend : ServerProcess : Process Log: Adding subtype manager WinUSBManager as part of AddAllSubtypeManagers.
2019-08-18T03:23:14.087Z : process : Process : Adding subtype manager WinUSBManager as part of AddAllSubtypeManagers.
2019-08-18T03:23:14.082Z : backend : ServerProcess : Process Log: Setting up Device Manager WinUSBManager
2019-08-18T03:23:14.087Z : process : Process : Setting up Device Manager WinUSBManager
2019-08-18T03:23:14.082Z : backend : ServerProcess : Process Log: Loading WinUSB Manager
2019-08-18T03:23:14.087Z : process : Process : Loading WinUSB Manager
2019-08-18T03:23:14.082Z : backend : ServerProcess : Process Log: Adding WinUSBManager subtype manager
2019-08-18T03:23:14.088Z : process : Process : Adding WinUSBManager subtype manager
2019-08-18T03:23:14.082Z : backend : ServerProcess : Process Log: Adding subtype manager XInputGamepadManager as part of AddAllSubtypeManagers.
2019-08-18T03:23:14.088Z : process : Process : Adding subtype manager XInputGamepadManager as part of AddAllSubtypeManagers.
2019-08-18T03:23:14.083Z : backend : ServerProcess : Process Log: Setting up Device Manager XInputGamepadManager
2019-08-18T03:23:14.088Z : process : Process : Setting up Device Manager XInputGamepadManager
2019-08-18T03:23:14.083Z : backend : ServerProcess : Process Log: Loading XInput Gamepad Manager
2019-08-18T03:23:14.088Z : process : Process : Loading XInput Gamepad Manager
2019-08-18T03:23:14.083Z : backend : ServerProcess : Process Log: Adding XInputGamepadManager subtype manager
2019-08-18T03:23:14.088Z : process : Process : Adding XInputGamepadManager subtype manager
2019-08-18T03:23:14.083Z : backend : ServerProcess : Process Log: Starting timed-repeat scanning for HidSharpManager
2019-08-18T03:23:14.088Z : process : Process : Starting timed-repeat scanning for HidSharpManager
2019-08-18T03:23:14.084Z : backend : ServerProcess : Process Log: Starting BLE Scanning
2019-08-18T03:23:14.088Z : process : Process : Starting BLE Scanning
2019-08-18T03:23:14.084Z : backend : ServerProcess : Process Log: Starting timed-repeat scanning for WinUSBManager
2019-08-18T03:23:14.088Z : process : Process : Starting timed-repeat scanning for WinUSBManager
2019-08-18T03:23:14.084Z : backend : ServerProcess : Process Log: Starting timed-repeat scanning for XInputGamepadManager
2019-08-18T03:23:14.088Z : process : Process : Starting timed-repeat scanning for XInputGamepadManager
2019-08-18T03:23:14.107Z : backend : ServerProcess : Process Log: Bluetooth Radio Information:
2019-08-18T03:23:14.107Z : process : Process : Bluetooth Radio Information:
2019-08-18T03:23:14.175Z : backend : ServerProcess : Process Log: BLE device found: LVS-Max210
2019-08-18T03:23:14.176Z : process : Process : BLE device found: LVS-Max210
2019-08-18T03:23:14.530Z : backend : ServerProcess : Process Log: Cannot find service 0000fff0-0000-1000-8000-00805f9b34fb of LVS-Max210.
2019-08-18T03:23:14.531Z : process : Process : Cannot find service 0000fff0-0000-1000-8000-00805f9b34fb of LVS-Max210.
2019-08-18T03:23:14.565Z : backend : ServerProcess : Process Log: Cannot find service 6e400001-b5a3-f393-e0a9-e50e24dcca9e of LVS-Max210.
2019-08-18T03:23:14.566Z : process : Process : Cannot find service 6e400001-b5a3-f393-e0a9-e50e24dcca9e of LVS-Max210.
2019-08-18T03:23:14.600Z : backend : ServerProcess : Process Log: Cannot find service 50300001-0024-4bd4-bbd5-a6920e4c5653 of LVS-Max210.
2019-08-18T03:23:14.601Z : process : Process : Cannot find service 50300001-0024-4bd4-bbd5-a6920e4c5653 of LVS-Max210.
2019-08-18T03:23:14.635Z : backend : ServerProcess : Process Log: Cannot find service 57300001-0023-4bd4-bbd5-a6920e4c5653 of LVS-Max210.
2019-08-18T03:23:14.635Z : process : Process : Cannot find service 57300001-0023-4bd4-bbd5-a6920e4c5653 of LVS-Max210.
2019-08-18T03:23:14.670Z : backend : ServerProcess : Process Log: Cannot find service 5a300001-0024-4bd4-bbd5-a6920e4c5653 of LVS-Max210.
2019-08-18T03:23:14.671Z : process : Process : Cannot find service 5a300001-0024-4bd4-bbd5-a6920e4c5653 of LVS-Max210.
2019-08-18T03:23:14.706Z : backend : ServerProcess : Process Log: Cannot find service 50300001-0023-4bd4-bbd5-a6920e4c5653 of LVS-Max210.
2019-08-18T03:23:14.707Z : process : Process : Cannot find service 50300001-0023-4bd4-bbd5-a6920e4c5653 of LVS-Max210.
2019-08-18T03:23:14.743Z : backend : ServerProcess : Process Log: Cannot find service 53300001-0023-4bd4-bbd5-a6920e4c5653 of LVS-Max210.
2019-08-18T03:23:14.743Z : process : Process : Cannot find service 53300001-0023-4bd4-bbd5-a6920e4c5653 of LVS-Max210.
2019-08-18T03:23:14.778Z : backend : ServerProcess : Process Log: Cannot find service 5a300001-0023-4bd4-bbd5-a6920e4c5653 of LVS-Max210.
2019-08-18T03:23:14.779Z : process : Process : Cannot find service 5a300001-0023-4bd4-bbd5-a6920e4c5653 of LVS-Max210.
2019-08-18T03:23:14.812Z : backend : ServerProcess : Process Log: Cannot find service 4f300001-0023-4bd4-bbd5-a6920e4c5653 of LVS-Max210.
2019-08-18T03:23:14.813Z : process : Process : Cannot find service 4f300001-0023-4bd4-bbd5-a6920e4c5653 of LVS-Max210.
2019-08-18T03:23:14.813Z : backend : ServerProcess : Process Log: No characteristics to connect to for device LVS-Max210
2019-08-18T03:23:14.813Z : process : Process : No characteristics to connect to for device LVS-Max210
2019-08-18T03:23:14.814Z : backend : ServerProcess : Process Log: Cannot connect to device LVS-Max210 249995015748772: No characteristics to connect to for device LVS-Max210 at Buttplug.Server.Managers.UWPBluetoothManager.UWPBluetoothDeviceInterface.<InitializeDevice>d__9.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Buttplug.Server.Managers.UWPBluetoothManager.UWPBluetoothDeviceInterface.<Create>d__7.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Buttplug.Server.Managers.UWPBluetoothManager.UWPBluetoothManager.<OnAdvertisementReceived>d__6.MoveNext()
2019-08-18T03:23:14.815Z : process : Process : Cannot connect to device LVS-Max210 249995015748772: No characteristics to connect to for device LVS-Max210 at Buttplug.Server.Managers.UWPBluetoothManager.UWPBluetoothDeviceInterface.<InitializeDevice>d__9.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Buttplug.Server.Managers.UWPBluetoothManager.UWPBluetoothDeviceInterface.<Create>d__7.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Buttplug.Server.Managers.UWPBluetoothManager.UWPBluetoothManager.<OnAdvertisementReceived>d__6.MoveNext()
2019-08-18T03:23:15.549Z : backend : ServerProcess : Process Log: Device='Bluetooth Device (Personal Area Network)',Manufacturer='Microsoft',DriverVersion='10.0.17134.1'
2019-08-18T03:23:15.550Z : process : Process : Device='Bluetooth Device (Personal Area Network)',Manufacturer='Microsoft',DriverVersion='10.0.17134.1'
2019-08-18T03:23:15.550Z : backend : ServerProcess : Process Log: Device='Microsoft Bluetooth Enumerator',Manufacturer='Microsoft',DriverVersion='10.0.17134.950'
2019-08-18T03:23:15.551Z : process : Process : Device='Microsoft Bluetooth Enumerator',Manufacturer='Microsoft',DriverVersion='10.0.17134.950'
2019-08-18T03:23:15.551Z : backend : ServerProcess : Process Log: Device='Bluetooth Device (RFCOMM Protocol TDI)',Manufacturer='Microsoft',DriverVersion='10.0.17134.1'
2019-08-18T03:23:15.551Z : process : Process : Device='Bluetooth Device (RFCOMM Protocol TDI)',Manufacturer='Microsoft',DriverVersion='10.0.17134.1'
2019-08-18T03:23:15.551Z : backend : ServerProcess : Process Log: Device='Microsoft Bluetooth LE Enumerator',Manufacturer='Microsoft',DriverVersion='10.0.17134.1'
2019-08-18T03:23:15.552Z : process : Process : Device='Microsoft Bluetooth LE Enumerator',Manufacturer='Microsoft',DriverVersion='10.0.17134.1'
2019-08-18T03:23:15.551Z : backend : ServerProcess : Process Log: Device='Generic Bluetooth Radio',Manufacturer='Cambridge Silicon Radio Ltd.',DriverVersion='10.0.17134.950'
2019-08-18T03:23:15.552Z : process : Process : Device='Generic Bluetooth Radio',Manufacturer='Cambridge Silicon Radio Ltd.',DriverVersion='10.0.17134.950'
2019-08-18T03:23:44.105Z : backend : ServerProcess : Process Log: Got JSON Message: [{"StopScanning":{"Id":4}}]
2019-08-18T03:23:44.107Z : process : Process : Got JSON Message: [{"StopScanning":{"Id":4}}]
2019-08-18T03:23:44.108Z : backend : ServerProcess : Process Log: Message successfully parsed as StopScanning type
2019-08-18T03:23:44.110Z : process : Process : Message successfully parsed as StopScanning type
2019-08-18T03:23:44.108Z : backend : ServerProcess : Process Log: Got Message 4 of type StopScanning to send
2019-08-18T03:23:44.110Z : process : Process : Got Message 4 of type StopScanning to send
2019-08-18T03:23:44.108Z : backend : ServerProcess : Process Log: Got StopScanning message.
2019-08-18T03:23:44.110Z : process : Process : Got StopScanning message.
2019-08-18T03:23:44.109Z : backend : ServerProcess : Process Log: Got StopScanning Message
2019-08-18T03:23:44.112Z : process : Process : Got StopScanning Message
2019-08-18T03:23:44.110Z : backend : ServerProcess : Process Log: Stopping timed-repeat scanning for HidSharpManager
2019-08-18T03:23:44.112Z : process : Process : Stopping timed-repeat scanning for HidSharpManager
2019-08-18T03:23:44.110Z : backend : ServerProcess : Process Log: Stopping BLE Scanning
2019-08-18T03:23:44.112Z : process : Process : Stopping BLE Scanning
2019-08-18T03:23:44.110Z : backend : ServerProcess : Process Log: Stopping timed-repeat scanning for WinUSBManager
2019-08-18T03:23:44.113Z : process : Process : Stopping timed-repeat scanning for WinUSBManager
2019-08-18T03:23:44.110Z : backend : ServerProcess : Process Log: Stopping timed-repeat scanning for XInputGamepadManager
2019-08-18T03:23:44.113Z : process : Process : Stopping timed-repeat scanning for XInputGamepadManager
2019-08-18T03:23:44.113Z : backend : ServerProcess : Process Log: Stopped BLE Scanning
2019-08-18T03:23:44.114Z : process : Process : Stopped BLE Scanning
</pre>
</details>
Here are the 3 services that chrome://bluetooth-internals/ lists for the device: 

Service UUID | Characteristic UUID | Properties
-- | -- | --
001-0023-4bd4-bbd5-a6920e4c5653 |   |  
  | 42300002-0023-4bd4-bbd5-a6920e4c5653 | Write Without Response, Write
  | 42300003-0023-4bd4-bbd5-a6920e4c5653 | Notify
00001801-0000-1000-8000-00805f9b34fb | No Characteristics Found |  
00001800-0000-1000-8000-00805f9b34fb |   |  
  | 00002a00-0000-1000-8000-00805f9b34fb | Read, Write
  | 00002a01-0000-1000-8000-00805f9b34fb | Read
  | 00002a04-0000-1000-8000-00805f9b34fb | Read
  | 00002aa6-0000-1000-8000-00805f9b34fb | Read

**Comment by prfeigan** [comment]
Solved by today's device config file update.

**Comment by qdot** [comment]
We were just missing the device UUID. Added to device config file and rev'd, now works via testing by reporter. Closing.
